name: 'Netlify'

on:
  issue_comment:
    types: [created]

jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    
    - name: Checkout repository!
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.issue.pull_request.head.sha }} 
    
    - name: Checkout Pull Request
      run: hub pr checkout ${{ github.event.issue.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
